name: Next.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # No need to export - Vercel will handle the deployment

      - name: Show build output
        run: |
          echo "Build directory contents:"
          ls -la .next
          ls -la out
          echo "Package.json contents:"
          cat package.json
